services:
  prestart:
    image: 'backend:latest'
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: bash scripts/prestart.sh
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - SKIP_PRESTART_DB=${SKIP_PRESTART_DB:-false}
      - SKIP_ALEMBIC=${SKIP_ALEMBIC:-false}

  backend:
    image: 'backend:latest'
    restart: always
    depends_on:
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - SKIP_PRESTART_DB=${SKIP_PRESTART_DB:-false}
      - SKIP_ALEMBIC=${SKIP_ALEMBIC:-false}
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile

  frontend:
    image: 'frontend:latest'
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=https://demoapi.srm-tech.com
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=https://demoapi.srm-tech.com
