name: Frontend - Build, Scan, Push & Deploy (Single ECR Repo)

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ecr.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/uat" ]]; then
            echo "ENV=uat" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/integration" ]]; then
            echo "ENV=int" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Load Env Config
        run: |
          if [[ "$ENV" == "prod" ]]; then
            echo "ECS_CLUSTER=${{ secrets.ECS_CLUSTER_PROD }}" >> $GITHUB_ENV
            echo "ECS_SERVICE=${{ secrets.ECS_SERVICE_FRONTEND_PROD }}" >> $GITHUB_ENV
            echo "TASK_DEF=${{ secrets.ECS_TASK_DEF_FRONTEND_PROD }}" >> $GITHUB_ENV
          elif [[ "$ENV" == "uat" ]]; then
            echo "ECS_CLUSTER=${{ secrets.ECS_CLUSTER_UAT }}" >> $GITHUB_ENV
            echo "ECS_SERVICE=${{ secrets.ECS_SERVICE_FRONTEND_UAT }}" >> $GITHUB_ENV
            echo "TASK_DEF=${{ secrets.ECS_TASK_DEF_FRONTEND_UAT }}" >> $GITHUB_ENV
          elif [[ "$ENV" == "int" ]]; then
            echo "ECS_CLUSTER=${{ secrets.ECS_CLUSTER_INT }}" >> $GITHUB_ENV
            echo "ECS_SERVICE=${{ secrets.ECS_SERVICE_FRONTEND_INT }}" >> $GITHUB_ENV
            echo "TASK_DEF=${{ secrets.ECS_TASK_DEF_FRONTEND_INT }}" >> $GITHUB_ENV
          fi

          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "ECR_REPO=${{ secrets.ECR_REPO }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
          | docker login \
          --username AWS \
          --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Set Version
        run: |
          VERSION=${GITHUB_SHA::7}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Frontend
        run: docker build -f frontend/Dockerfile -t frontend:$VERSION .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Frontend
        run: trivy image --scanners vuln --ignore-unfixed --exit-code 1 --severity CRITICAL frontend:$VERSION

      - name: Tag Image
        run: |
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO

          docker tag frontend:$VERSION $IMAGE_URI:frontend-$VERSION
          docker tag frontend:$VERSION $IMAGE_URI:frontend-$ENV-latest

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Image
        run: |
          docker push $IMAGE_URI:frontend-$VERSION
          docker push $IMAGE_URI:frontend-$ENV-latest

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Task Definition
        run: |
          aws ecs describe-task-definition \
          --task-definition $TASK_DEF \
          --query taskDefinition > task.json

      - name: Update Task Definition
        run: |
          jq --arg FRONT "$IMAGE_URI:frontend-$VERSION" \
             '
             .containerDefinitions |= map(
               if .name == "frontend" then .image = $FRONT else . end
             )
             ' task.json > new-task.json

      - name: Register Task
        run: |
          aws ecs register-task-definition \
          --cli-input-json file://new-task.json

      - name: Deploy to ECS
        if: env.ENV != 'dev'
        run: |
          aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment
